---
- name: Update and upgrade APT packages
  apt:
    update_cache: true
    upgrade: true

- name: Add Hashicorp Stable APT repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: [deb]
    uris: "https://apt.releases.hashicorp.com"
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [main]
    state: present
    enabled: true

- name: Add VSCode APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: true

- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    state: present
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    signed_by: "https://download.docker.com/linux/debian/gpg"
    enabled: true

- name: Add pgAdmin APT repository
  ansible.builtin.deb822_repository:
    name: pgadmin
    types: [deb]
    uris: "https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release }}"
    suites: [pgadmin4]
    components: [main]
    signed_by: "https://www.pgadmin.org/static/packages_pgadmin_org.pub"
    state: present
    enabled: true

- name: Add Kubernetes APT repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/"
    signed_by: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
    suites: [/]
    state: present
    enabled: true
