---
- name: Install latest packages on Debian-based hosts
  hosts: localhost
  become: true

  tasks:
    - name: Ensure all 3rd-party apt repos in place
      include_tasks: add_apt_repos.yml

    - name: Ensure latest media packages installed
      apt:
        name:
          - audacious
          - mpv
          - transgui
          - vlc
        state: latest
        update_cache: true

    - name: Ensure WineHQ stable package installed with recommended packages
      apt:
        name: winehq-stable
        state: present
        install_recommends: true
        update_cache: true

    - name: Ensure latest techy packages installed
      apt:
        name:
          - cifs-utils
          - code
          - containerd.io
          - curl
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - git
          - gpg
          - htop
          - iperf
          - jq
          - kdeconnect
          - kubectl
          - nano
          - openssh-server
          - pgadmin4-desktop
          - python3-pip
          - redis-tools
          - terraform
          - unattended-upgrades
          - unzip
          - vault
          - wget
          - wireguard
        state: latest
        update_cache: true

    # Unconventional installs
    - name: Download AWS CLI installer zip
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscli.zip"
        mode: '0644'

    - name: Unzip AWS CLI installer
      unarchive:
        src: "/tmp/awscli.zip"
        dest: "/tmp"

    - name: Install AWS CLI
      command: "/tmp/aws/install --update"
      changed_when: false

    - name: Download bitwarden CLI zip
      get_url:
        url: "https://vault.bitwarden.com/download/?app=cli&platform=linux"
        dest: "/tmp/bw.zip"
        mode: '0644'

    - name: Unzip bitwarden CLI
      unarchive:
        src: "/tmp/bw.zip"
        dest: "/usr/local/bin"

    # Python
    - name: Ensure latest python modules installed
      pip:
        name:
          - yt-dlp
        state: latest
      become: false

    # Into the weeds
    - name: Ensure dan part of the docker group
      user:
        name: dan
        groups: docker
        append: true
        state: present

    - name: One-off commands, run as dan
      command: "{{ item }}"
      loop:
        - git config --global init.defaultBranch main
        - git config --global user.name "Daniel Knobloch"
      changed_when: false
      become: false
