---
- name: Install latest packages on Linux Mint
  hosts: localhost
  become: true

  tasks:
    - name: Ensure these are gone
      apt:
        name:
          - celluloid
          - hypnotix
          - matrix
          - rhythmbox
          - thunderbird
        state: absent
