---
- name: Install latest packages on Debian-based hosts
  hosts: localhost
  become: true

  tasks:
    - name: Stop snapd
      ansible.builtin.service:
        name: snapd
        state: stopped
        enabled: false

    - name: Ensure these are gone
      apt:
        name:
          - snapd
          - thunderbird
        state: absent
