---
- name: Set passwordless sudo for user 'dan'
  hosts: localhost
  become: true
  tasks:
    - name: Add user 'dan' to the sudo group
      user:
        name: dan
        groups: sudo
        append: true

    - name: Configure passwordless sudo for 'dan'
      copy:
        dest: /etc/sudoers.d/dan
        content: "dan ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'
        owner: root
        group: root

    - name: Validate sudoers file for syntax errors
      command: visudo -cf /etc/sudoers.d/dan
      register: visudo_check
      changed_when: false
      failed_when: visudo_check.rc != 0

    - name: Ensure sudoers.d directory has correct permissions
      file:
        path: /etc/sudoers.d
        mode: '0750'
        recurse: true
